export default {
  login: '7',
  id: 6599979,
  node_id: 'MDQ6VXNlcjY1OTk5Nzk=',
  avatar_url: 'https://avatars2.githubusercontent.com/u/6599979?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/DeveVivek',
  html_url: 'https://github.com/DeveVivek',
  followers_url: 'https://api.github.com/users/DeveVivek/followers',
  following_url: 'https://api.github.com/users/DeveVivek/following{/other_user}',
  gists_url: 'https://api.github.com/users/DeveVivek/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/DeveVivek/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/DeveVivek/subscriptions',
  organizations_url: 'https://api.github.com/users/DeveVivek/orgs',
  repos_url: 'https://api.github.com/users/DeveVivek/repos',
  events_url: 'https://api.github.com/users/DeveVivek/events{/privacy}',
  received_events_url: 'https://api.github.com/users/DeveVivek/received_events',
  type: 'User',
  site_admin: false,
  name: 'Brittany Chiang',
  company: '@Upstatement ',
  blog: 'https://brittanychiang.com',
  location: 'Boston, MA',
  email: null,
  hireable: true,
  bio: null,
  public_repos: 53,
  public_gists: 4,
  followers: 248,
  following: 12,
  created_at: '2014-02-05T23:22:59Z',
  updated_at: '2019-04-17T03:18:31Z',
};
